---
- name: Add/update pg_ctl.conf
  ansible.builtin.blockinfile:
    path: /etc/postgresql/{{ postgresql_version }}/main/pg_ctl.conf
    block: "{{ postgresql_pg_ctl_cfg }}"
  notify: restart postgresql
- name: Add/update pg_hba.conf
  ansible.builtin.blockinfile:
    path: /etc/postgresql/{{ postgresql_version }}/main/pg_hba.conf
    block: "{{ postgresql_pg_hba_cfg }}"
  notify: restart postgresql
- name: Add/update pg_ident.conf
  ansible.builtin.blockinfile:
    path: /etc/postgresql/{{ postgresql_version }}/main/pg_ident.conf
    block: "{{ postgresql_pg_ident_cfg }}"
  notify: restart postgresql
- name: Create/update setting file
  ansible.builtin.template:
    src: custom.conf.j2
    dest: /etc/postgresql/{{ postgresql_version }}/main/conf.d/custom.conf
    owner: postgres
    group: postgres
    mode: "0644"
  notify: restart postgresql
