---
- name: Create/update setting file
  ansible.builtin.template:
    src: postgresql.j2
    dest: /erc/postgresql/postgresql.conf
    mode: "0644"
- name: Add/update option setting
  ansible.builtin.lineinfile:
    path: /etc/postgresql/postgresql.conf
    regexp: ^(#\\s+)?option_name=
    line: option_name=option_value
- name: Add/update custom setting
  ansible.builtin.blockinfile:
    path: /etc/postgresql/postgresql.conf
    block: "{{ role_extra_cfg }}"
