---
- name: Create/remove databases
  community.postgresql.postgresql_db:
    name: "{{ item.name }}"
    encoding: "{{ item.encoding | default(postgresql_default_charset) }}"
    state: "{{ item.state | default(true) | ternary('present', 'absent') }}"
    # login_unix_socket: "{{ mariadb_unix_socket_path }}"
  loop: "{{ postgresql_databases }}"
  loop_control:
    label: "{{ item.name }}"
