---
- name: Create/remove databases
  become: true
  become_user: postgres
  no_log: true
  block:
    - name: Create/remove PosrgreSQL users
      community.postgresql.postgresql_user:
        name: "{{ item.name }}"
        password: "{{ item.password }}"
        db: "{{ item.db | default(omit) }}"
        state: "{{ item.state | default(true) | ternary('present', 'absent') }}"
      loop: "{{ postgresql_users }}"
      loop_control:
        label: "{{ item.name }}"
