---
- name: restart postgresql
  ansible.builtin.systemd_service:
    state: restarted
    name: postgresql
- name: reload postgresql
  ansible.builtin.systemd_service:
    state: reloaded
    name: postgresql
