---
- name: Verify
  hosts: all
  gather_facts: true
  check_mode: true
  become: true
  tasks:
    ## パッケージのテスト
    - name: Gather the package facts
      ansible.builtin.package_facts:
        manager: auto
    - name: Assert package
      ansible.builtin.assert:
        that:
          - "ansible_facts.packages['postgresql'] is defined"
          - "ansible_facts.packages['python3-psycopg2'] is defined"
          - "ansible_facts.packages['acl'] is defined"
        fail_msg: "Required PostgreSQL packages are not installed"
        success_msg: "All required PostgreSQL packages are installed"
    ## ユーザーのテスト
    - name: Add user check
      ansible.builtin.user:
        name: postgres
      register: result
    - name: Assert user
      ansible.builtin.assert:
        that: result is not changed
        fail_msg: "User postgres is not properly configured"
        success_msg: "User postgres is properly configured"
    ## グループのテスト
    - name: Add group check
      ansible.builtin.group:
        name: postgres
      register: result
    - name: Assert group
      ansible.builtin.assert:
        that: result is not changed
        fail_msg: "Group postgres is not properly configured"
        success_msg: "Group postgres is properly configured"
    ## サービスのテスト
    - name: Populate service facts
      ansible.builtin.service_facts:
    - name: Assert service(postgresql)
      ansible.builtin.assert:
        that:
          - ansible_facts.services['postgresql.service'] is defined
          - ansible_facts.services['postgresql.service']['status'] == 'enabled'
        fail_msg: "postgresql service is not enabled"
        success_msg: "postgresql service is enabled"
    ## 待受ポートのテスト
    - name: Gather facts on listening ports
      community.general.listen_ports_facts:
        command: ss
    - name: Set assert variables
      ansible.builtin.set_fact:
        listen_tcp_posts: "{{ ansible_facts.tcp_listen | map(attribute='port') | unique | list }}"
        listen_udp_posts: "{{ ansible_facts.udp_listen | map(attribute='port') | unique | list }}"
    - name: Assert listen port
      ansible.builtin.assert:
        that:
          - 5432 in listen_tcp_posts
        fail_msg: "Port 5432 is not listening"
        success_msg: "Port 5432 is listening"
