---
- name: Verify
  hosts: all
  gather_facts: true
  check_mode: true
  become: true
  tasks:
    ## パッケージのテスト
    - name: Gather the package facts
      ansible.builtin.package_facts:
        manager: auto
    - name: Assert package
      ansible.builtin.assert:
        that:
          - ansible_facts.packages['postgresql']
          - ansible_facts.packages['python3-psycopg2']
          - ansible_facts.packages['acl']
    ## ユーザーのテスト
    - name: Add user check
      ansible.builtin.user:
        name: postgres
      register: result
    - name: Assert user
      ansible.builtin.assert:
        that: result is not changed
    ## グループのテスト
    - name: Add group check
      ansible.builtin.group:
        name: postgres
      register: result
    - name: Assert group
      ansible.builtin.assert:
        that: result is not changed
    ## サービスのテスト
    - name: Populate service facts
      ansible.builtin.service_facts:
    - name: Assert service(postgresql)
      ansible.builtin.assert:
        that:
          - ansible_facts.services['postgresql.service']
          - ansible_facts.services['postgresql.service']['status'] == 'enabled'
    - name: Assert service(bullseye)
      ansible.builtin.assert:
        that:
          - ansible_facts.services['postgresql@13-main.service']
          - ansible_facts.services['postgresql@13-main.service']['state'] == 'running'
      when: ansible_facts.distribution_major_version == '11'
    - name: Assert service(buster)
      ansible.builtin.assert:
        that:
          - ansible_facts.services['postgresql@11-main.service']
          - ansible_facts.services['postgresql@11-main.service']['state'] == 'running'
      when: ansible_facts.distribution_major_version == '10'
    ## 待受ポートのテスト
    - name: Gather facts on listening ports
      community.general.listen_ports_facts:
        command: ss
    - name: Set assert variables
      ansible.builtin.set_fact:
        listen_tcp_posts: "{{ ansible_facts.tcp_listen | map(attribute='port') | unique | list }}"
        listen_udp_posts: "{{ ansible_facts.udp_listen | map(attribute='port') | unique | list }}"
    - name: Assert listen port
      ansible.builtin.assert:
        that:
          - 5432 in listen_tcp_posts
