---
- name: Verify
  hosts: all
  gather_facts: true
  become: true
  tasks:
    ## パッケージのテスト
    - name: Gather the package facts
      ansible.builtin.package_facts:
        manager: auto
    - name: Assert package
      ansible.builtin.assert:
        that:
          - "ansible_facts.packages['postgresql'] is defined"
          - "ansible_facts.packages['python3-psycopg2'] is defined"
          - "ansible_facts.packages['acl'] is defined"
        fail_msg: "Required PostgreSQL packages are not installed"
        success_msg: "All required PostgreSQL packages are installed"
    ## ユーザーのテスト
    - name: Get user facts
      ansible.builtin.getent:
        database: passwd
        key: postgres
    - name: Assert user
      ansible.builtin.assert:
        that: getent_passwd['postgres'] is defined
        fail_msg: "User postgres does not exist"
        success_msg: "User postgres exists"
    ## グループのテスト
    - name: Get group facts
      ansible.builtin.getent:
        database: group
        key: postgres
    - name: Assert group
      ansible.builtin.assert:
        that: getent_group['postgres'] is defined
        fail_msg: "Group postgres does not exist"
        success_msg: "Group postgres exists"
    ## サービスのテスト
    - name: Populate service facts
      ansible.builtin.service_facts:
    - name: Assert service(postgresql)
      ansible.builtin.assert:
        that:
          - ansible_facts.services['postgresql.service'] is defined
          - ansible_facts.services['postgresql.service']['status'] == 'enabled'
        fail_msg: "postgresql service is not enabled"
        success_msg: "postgresql service is enabled"
    ## 待受ポートのテスト
    - name: Gather facts on listening ports
      community.general.listen_ports_facts:
        command: ss
    - name: Set assert variables
      ansible.builtin.set_fact:
        listen_tcp_posts: "{{ ansible_facts.tcp_listen | map(attribute='port') | unique | list }}"
        listen_udp_posts: "{{ ansible_facts.udp_listen | map(attribute='port') | unique | list }}"
    - name: Assert listen port
      ansible.builtin.assert:
        that:
          - 5432 in listen_tcp_posts
        fail_msg: "Port 5432 is not listening"
        success_msg: "Port 5432 is listening"
