---
- name: Service PostgreSQL is active and enabled on system startup
  ansible.builtin.systemd_service:
    name: postgresql
    state: started
    enabled: true
- name: Ensure allow PostgreSQL port
  community.general.ufw:
    rule: allow
    port: "5432"
    proto: tcp
  when: posgresql_allow_connect_other_host | default(false)
