---
- name: Service postgresql is active and enabled on system startup
  ansible.builtin.systemd:
    name: postgresql
    state: started
    enabled: true
# - name: allow postgresql port
#  community.general.ufw:
#    rule: allow
#    port: "123456"
